#!/usr/bin/env node
import { spawnSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import readline from 'node:readline/promises'
import { stdin as input, stdout as output } from 'node:process'

const args = new Set(process.argv.slice(2))
const dryRun = args.has('--dry-run')
const assumeYes = args.has('--yes') || args.has('-y')
const help = args.has('--help') || args.has('-h')

const envPath = '.env.local'
const examplePath = '.env.example'

if (help) {
  console.log(`ConvexKit setup wizard

Usage:
  npm run setup
  npm run setup -- --dry-run
  npm run setup -- --yes

Options:
  --dry-run   Print the generated .env.local without writing files or running Convex commands.
  --yes, -y   Use defaults for prompts. Useful for CI smoke tests.
  --help, -h  Show this help.
`)
  process.exit(0)
}

const rl = readline.createInterface({ input, output })

function parseEnvFile(path) {
  if (!existsSync(path)) return {}

  return Object.fromEntries(
    readFileSync(path, 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => {
        const index = line.indexOf('=')
        const key = line.slice(0, index).trim()
        const value = line
          .slice(index + 1)
          .trim()
          .replace(/^["']|["']$/g, '')
        return [key, value]
      })
  )
}

async function prompt(label, defaultValue = '') {
  if (assumeYes) return defaultValue

  const suffix = defaultValue ? ` (${defaultValue})` : ''
  const answer = await rl.question(`${label}${suffix}: `)
  return answer.trim() || defaultValue
}

async function confirm(label, defaultValue = false) {
  if (assumeYes) return defaultValue

  const suffix = defaultValue ? 'Y/n' : 'y/N'
  const answer = (await rl.question(`${label} [${suffix}]: `)).trim().toLowerCase()
  if (!answer) return defaultValue
  return answer === 'y' || answer === 'yes'
}

function generateSecret() {
  return randomBytes(32).toString('base64url')
}

function realValue(value) {
  if (!value) return ''
  if (value.startsWith('your-')) return ''
  return value
}

function serializeEnv(values) {
  return `# ConvexKit local environment
# Generated by npm run setup.

# --------------- Convex ---------------
CONVEX_DEPLOYMENT=${values.CONVEX_DEPLOYMENT}
VITE_CONVEX_URL=${values.VITE_CONVEX_URL}
VITE_CONVEX_SITE_URL=${values.VITE_CONVEX_SITE_URL}

# --------------- Better Auth ---------------
BETTER_AUTH_SECRET=${values.BETTER_AUTH_SECRET}
SITE_URL=${values.SITE_URL}

# --------------- Google OAuth (optional) ---------------
GOOGLE_CLIENT_ID=${values.GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${values.GOOGLE_CLIENT_SECRET}
VITE_GOOGLE_AUTH_ENABLED=${values.VITE_GOOGLE_AUTH_ENABLED}

# --------------- Cloudflare (optional deploy) ---------------
CLOUDFLARE_API_TOKEN=${values.CLOUDFLARE_API_TOKEN}
CLOUDFLARE_ACCOUNT_ID=${values.CLOUDFLARE_ACCOUNT_ID}
CUSTOM_DOMAIN=${values.CUSTOM_DOMAIN}

# --------------- App Config ---------------
VITE_APP_ENV=${values.VITE_APP_ENV}
VITE_SENTRY_DSN=${values.VITE_SENTRY_DSN}
`
}

function runConvexEnvSet(name, value) {
  if (!value) return true

  const result = spawnSync('npx', ['convex', 'env', 'set', name, value], {
    stdio: 'inherit',
    shell: false,
  })

  return result.status === 0
}

try {
  const existing = parseEnvFile(envPath)
  const example = parseEnvFile(examplePath)
  const defaults = { ...example, ...existing }

  console.log('ConvexKit setup')
  console.log('This creates .env.local and can optionally set Convex backend env vars.\n')

  if (existsSync(envPath) && !dryRun) {
    const overwrite = await confirm(`${envPath} already exists. Overwrite it?`, false)
    if (!overwrite) {
      console.log('Setup cancelled without changes.')
      process.exit(0)
    }
  }

  const values = {
    CONVEX_DEPLOYMENT: await prompt(
      'Convex deployment name',
      defaults.CONVEX_DEPLOYMENT || 'dev:your-deployment-name'
    ),
    VITE_CONVEX_URL: await prompt(
      'Convex realtime URL',
      defaults.VITE_CONVEX_URL || 'https://your-deployment.convex.cloud'
    ),
    VITE_CONVEX_SITE_URL: await prompt(
      'Convex site/auth URL',
      defaults.VITE_CONVEX_SITE_URL || 'https://your-deployment.convex.site'
    ),
    BETTER_AUTH_SECRET: defaults.BETTER_AUTH_SECRET?.startsWith('your-')
      ? generateSecret()
      : defaults.BETTER_AUTH_SECRET || generateSecret(),
    SITE_URL: await prompt('App URL', defaults.SITE_URL || 'http://localhost:3000'),
    GOOGLE_CLIENT_ID: '',
    GOOGLE_CLIENT_SECRET: '',
    VITE_GOOGLE_AUTH_ENABLED: 'false',
    CLOUDFLARE_API_TOKEN: realValue(defaults.CLOUDFLARE_API_TOKEN),
    CLOUDFLARE_ACCOUNT_ID: realValue(defaults.CLOUDFLARE_ACCOUNT_ID),
    CUSTOM_DOMAIN: defaults.CUSTOM_DOMAIN || '',
    VITE_APP_ENV: defaults.VITE_APP_ENV || 'development',
    VITE_SENTRY_DSN: defaults.VITE_SENTRY_DSN || '',
  }

  const configureGoogle = await confirm('Configure Google OAuth now?', false)
  if (configureGoogle) {
    values.GOOGLE_CLIENT_ID = await prompt('Google client ID', defaults.GOOGLE_CLIENT_ID || '')
    values.GOOGLE_CLIENT_SECRET = await prompt(
      'Google client secret',
      defaults.GOOGLE_CLIENT_SECRET || ''
    )
    values.VITE_GOOGLE_AUTH_ENABLED =
      values.GOOGLE_CLIENT_ID && values.GOOGLE_CLIENT_SECRET ? 'true' : 'false'
  }

  const contents = serializeEnv(values)

  if (dryRun) {
    console.log(`\n--- ${envPath} preview ---`)
    console.log(contents)
  } else {
    writeFileSync(envPath, contents)
    console.log(`\nWrote ${envPath}`)
  }

  const shouldSetConvexEnv =
    !dryRun && (await confirm('Set backend env vars on the current Convex deployment?', false))

  if (shouldSetConvexEnv) {
    const entries = [
      ['BETTER_AUTH_SECRET', values.BETTER_AUTH_SECRET],
      ['SITE_URL', values.SITE_URL],
      ['GOOGLE_CLIENT_ID', values.GOOGLE_CLIENT_ID],
      ['GOOGLE_CLIENT_SECRET', values.GOOGLE_CLIENT_SECRET],
    ]

    let ok = true
    for (const [name, value] of entries) {
      if (!value) continue
      ok = runConvexEnvSet(name, value) && ok
    }

    if (!ok) {
      console.error(
        '\nSome Convex env vars failed to set. Re-run the commands manually after login.'
      )
      process.exitCode = 1
    }
  } else if (!dryRun) {
    console.log('\nSkipped Convex backend env setup.')
    console.log('Run these later after `npx convex login` if needed:')
    console.log('  npx convex env set BETTER_AUTH_SECRET "<value>"')
    console.log('  npx convex env set SITE_URL "<value>"')
    console.log('  npx convex env set GOOGLE_CLIENT_ID "<value>"')
    console.log('  npx convex env set GOOGLE_CLIENT_SECRET "<value>"')
  }

  console.log('\nNext steps:')
  console.log('  npm run dev')
  console.log('  Open http://localhost:3000')
} finally {
  rl.close()
}
