/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesFormsRouteImport } from './routes/examples.forms'
import { Route as ExamplesFilesRouteImport } from './routes/examples.files'
import { Route as ExamplesChatRouteImport } from './routes/examples.chat'
import { Route as ExamplesAdminRouteImport } from './routes/examples.admin'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesFormsRoute = ExamplesFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesFilesRoute = ExamplesFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesChatRoute = ExamplesChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesAdminRoute = ExamplesAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ExamplesRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/examples/admin': typeof ExamplesAdminRoute
  '/examples/chat': typeof ExamplesChatRoute
  '/examples/files': typeof ExamplesFilesRoute
  '/examples/forms': typeof ExamplesFormsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/examples/admin': typeof ExamplesAdminRoute
  '/examples/chat': typeof ExamplesChatRoute
  '/examples/files': typeof ExamplesFilesRoute
  '/examples/forms': typeof ExamplesFormsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/examples/admin': typeof ExamplesAdminRoute
  '/examples/chat': typeof ExamplesChatRoute
  '/examples/files': typeof ExamplesFilesRoute
  '/examples/forms': typeof ExamplesFormsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples'
    | '/dashboard'
    | '/files'
    | '/examples/admin'
    | '/examples/chat'
    | '/examples/files'
    | '/examples/forms'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples'
    | '/dashboard'
    | '/files'
    | '/examples/admin'
    | '/examples/chat'
    | '/examples/files'
    | '/examples/forms'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/examples'
    | '/_authenticated/dashboard'
    | '/_authenticated/files'
    | '/examples/admin'
    | '/examples/chat'
    | '/examples/files'
    | '/examples/forms'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ExamplesRoute: typeof ExamplesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/forms': {
      id: '/examples/forms'
      path: '/forms'
      fullPath: '/examples/forms'
      preLoaderRoute: typeof ExamplesFormsRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/files': {
      id: '/examples/files'
      path: '/files'
      fullPath: '/examples/files'
      preLoaderRoute: typeof ExamplesFilesRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/chat': {
      id: '/examples/chat'
      path: '/chat'
      fullPath: '/examples/chat'
      preLoaderRoute: typeof ExamplesChatRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/admin': {
      id: '/examples/admin'
      path: '/admin'
      fullPath: '/examples/admin'
      preLoaderRoute: typeof ExamplesAdminRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ExamplesRouteChildren {
  ExamplesAdminRoute: typeof ExamplesAdminRoute
  ExamplesChatRoute: typeof ExamplesChatRoute
  ExamplesFilesRoute: typeof ExamplesFilesRoute
  ExamplesFormsRoute: typeof ExamplesFormsRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  ExamplesAdminRoute: ExamplesAdminRoute,
  ExamplesChatRoute: ExamplesChatRoute,
  ExamplesFilesRoute: ExamplesFilesRoute,
  ExamplesFormsRoute: ExamplesFormsRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ExamplesRoute: ExamplesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
